name: Package addon

on:
  push:
    branches:
      - locale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q
          config: https://raw.githubusercontent.com/BigWigsMods/BigWigs/master/.luacheckrc

      - name: Download common locale
        if: always()
        run: |
          mkdir -p Core/Locales
          curl -sS https://raw.githubusercontent.com/BigWigsMods/BigWigs/master/Core/Locales/common.enUS.lua > Core/Locales/common.enUS.lua

      - name: Update option files
        if: always()
        uses: BigWigsMods/actions/gen-options@master

      - name: Clean up common locale
        if: always()
        run: |
          rm -r Core/Locales

      - name: Package
        uses: BigWigsMods/packager@master
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: LittleWigs-${{ github.sha }}
          path: .release/
